import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/page";
import StoreProvider from "./StoreProvider";
import LoginPage from "@/components/login/page";
import Footer from "@/components/footer/page";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased `}>
        <StoreProvider>
          <Header />
          <LoginPage />

          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
